### ISSUE TITLE
First timer

### ISSUE THREAD

**Issue by hannydevelop** [bancodobrasil/stop-analyzing#10]
I am a full stack junior developer (MEVN) I'll love to contribute to this project,  please let me know if you have any task that falls in my stack: 
P. S : this is the first time am contributing to an open source project

**Comment by tiagostutz** [comment]
Hi there @hannydevelop !! 👋🏻 

Welcome to Stop Analyzing. We are so glad to have you here and it will be such an honor to have the first contribution of someone I'm sure will be a Open Source Rockstar 🌟 😃 ...! 

I'm sure we will build together such a great and useful product. In https://github.com/bancodobrasil/stop-analyzing/issues/2 you will find a discussion that can give some background on the project.

I'm creating an issue for you right now. The [backend](https://github.com/bancodobrasil/stop-analyzing-api) is in Go and [frontend](https://github.com/bancodobrasil/stop-analyzing-embed) is in React. I think that even if you currently work with Vue and not React, I can craft an issue for you that you will be able to work on the frontend. If you prefer a backend task, please let me know. Don't worry, I'll guide you all the way through your contribution. There are other contributors that don't work with React and are making their first contributions to this project and making it happen. As you may have seen, this is a project specially designed for beginners.

So, I'll create an issue for you in the frontend and will link it here for you to take a look and get started. 
Sounds good?

**Comment by hannydevelop** [comment]
Ï am super excited  i Will be making my first contribution on an open source project, It sounds amazing and won't be a bad idea to work with you

**Comment by eduardomrodrigues** [comment]
Welcome, @hannydevelop !!!

**Comment by tiagostutz** [comment]
@hannydevelop I've opened this issue for you: https://github.com/bancodobrasil/stop-analyzing-embed/issues/53
It's a simple issue, but I think it will be good for you to get started with the project. If you need some help run the project locally, please free feel to ask on the issue and me or someone will come to help.

Are you used to the Fork/Merge process? Need some help on that?

Don't hesitate to ask if you have any doubt.

**Comment by hannydevelop** [comment]
I Will work on this definately !
Looking  forward to working with you

**Comment by tiagostutz** [comment]
Awesome, @hannydevelop !
Please, comment on the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/53 so I can assign it to you. 

Thanks!

**Comment by hannydevelop** [comment]
I just commented on It

**Comment by hannydevelop** [comment]
> @hannydevelop I've opened this issue for you: [bancodobrasil/stop-analyzing-embed#53](https://github.com/bancodobrasil/stop-analyzing-embed/issues/53)
> It's a simple issue, but I think it will be good for you to get started with the project. If you need some help run the project locally, please free feel to ask on the issue and me or someone will come to help.
> 
> Are you used to the Fork/Merge process? Need some help on that?
> 
> Don't hesitate to ask if you have any doubt.

Hello tiagostutz do you think there's another issue I could work on? then open an issue for me as I'll be super glad to work on it!
Thanks, I just became part of the team

**Comment by tiagostutz** [comment]
Hi there @hannydevelop !!  Thanks for accept being part of the team. I’m sure we are building a great tool together.

Sure, I’ll open an issue for you asap. You said you can work with NodeJS also, right? Would you like to work on a mock server? If so, I’ll open the issue with the spec details and link that for you here.

**Comment by hannydevelop** [comment]
> Hi there @hannydevelop !! Thanks for accept being part of the team. I’m sure we are building a great tool together.!!
> 
> Sure, I’ll open an issue for you asap. You said you can work with NodeJS also, right? Would you like to work on a mock server? If so, I’ll open the issue with the spec details and link that for you here.
> 
> What do you think?

That's fine!
I work with node js, looking forward to contribute to the mock server!

**Comment by tiagostutz** [comment]
Awesome, @hannydevelop !

I have just created and assigned to you the issue https://github.com/bancodobrasil/stop-analyzing-embed/issues/58 
If you have any doubt or need any help, please feel free to ask there and we will come by.

Thanks for being such an enthusiastic member, really appreciate 🚀
