### ISSUE TITLE
Some Mistakes in README.md

### ISSUE THREAD

**Issue by reinaldocomputer** [bancodobrasil/stop-analyzing#12]
Read the text and correct some misspelling and grammar mistakes.

Some errors identified:

Current: like a product of you e-commerce
Correction: like a product of your e-commerce

Current: There are 3 projects you can contribute to:
Correction: There are 2 projects you can contribute to:

**Comment by tiagostutz** [comment]
Hello @reinaldocomputer !! Welcome to stop analyzing...!
Sorry for taking so long to answer, I hope you are doing well there.

Thanks for you contribution and please feel free to open a PR with those fixes. I've just assigned that issue to you.

Go for it! 🚀

**Comment by yash0501** [comment]
Can I also work on this issue?

**Comment by reinaldocomputer** [comment]
Hey @tiagostutz thank you for your answer.
It will be a pleasure contribute in this project.

My pull request:
https://github.com/bancodobrasil/stop-analyzing/pull/14

@yash0501 feel free for helping

Thank you guys

**Comment by raunakpriya** [comment]
Hey, can I work on this issue?

**Comment by sakshi006** [comment]
Hey @reinaldocomputer  Can I work on this issue?

**Comment by sakshi006** [comment]
Hey!
Can i work on this issue?
