### ISSUE TITLE
I would like to help

### ISSUE THREAD

**Issue by KarineValenca** [bancodobrasil/stop-analyzing#15]
Hi, everyone! I would like to contribute to this project! I'm a fullstack developer, also I have some experience contributing to OpenSource, so maybe I can help other users that want to contribute as well. 

Looking forward to contributing! Thanks!

**Comment by tiagostutz** [comment]
Hi @KarineValenca ! Welcome to stop analyzing 👋🏻 
Thanks for offering some help here. 

As you have some experience contributing to Open Source, you could take a look and review this PR (https://github.com/bancodobrasil/stop-analyzing-embed/pull/111). What do you think?

Have you checked the https://github.com/bancodobrasil/stop-analyzing/issues/2 that gives more details on the main goals of the project?

**Comment by tiagostutz** [comment]
@KarineValenca, also there is this issue you could also take a look at, if you may: https://github.com/bancodobrasil/stop-analyzing-api/issues/27

**Comment by KarineValenca** [comment]
Hi @tiagostutz!
Yes, I checked #2, very interesting project. I'll take a look at the issue and the PR. 

Thank you!
