### ISSUE TITLE
I would like to help

### ISSUE THREAD

**Issue by tbfreitas** [bancodobrasil/stop-analyzing#16]
@tiagostutz I thought this project has a huge potential and so I am grateful if I can help you.
Can you pass me some issue to work on it?

**Comment by tiagostutz** [comment]
Hi there, @tbfreitas !

Thanks for offering help. We have two projects that build ups Stop Analyzing:
- https://github.com/bancodobrasil/stop-analyzing-embed/
- https://github.com/bancodobrasil/stop-analyzing-api

I think you could help by welcoming and organizing issues to first-timers and beginners that asks for issues, like https://github.com/bancodobrasil/stop-analyzing-api/issues/30, https://github.com/bancodobrasil/stop-analyzing-embed/issues/135 and https://github.com/bancodobrasil/stop-analyzing-embed/issues/134

First, please take a look at the [Poppins Manifesto](https://github.com/bancodobrasil/poppins) and look for some closed issues and PRs to have a reference on how the Poppins dynamic goes.

Of course, the first thing to do is to put the projects to run locally, but them you can start attending the contributors that arrive asking for an issue to tackle.

If you need any assistance, please let me know. =)

**Comment by tbfreitas** [comment]
Hi, @tiagostutz .

Sure I can do it, with pleasure.

I'll take a closer look at the Poppins Manifesto, whereas beginning the task once I got a complete understanding of its pattern.
I will report any doubts here, ok ?  🆘

**Comment by tiagostutz** [comment]
Absolutely.! Go ahead.
