### ISSUE TITLE
New contributions

### ISSUE THREAD

**Issue by lbenicio-ibm** [bancodobrasil/stop-analyzing#18]
Hi, 

Great repository! i would like to contribute to the project. 

What could i do to help?

cheers!

**Comment by tiagostutz** [comment]
Hi there @lbenicio-ibm !! 👋🏻 
Welcome to Stop Analyzing. It will be nice to have your contributions here.

If you want to go into a Golang world, I think this is a good start:
https://github.com/bancodobrasil/stop-analyzing-api/issues/26

Let's get something for you to tackle. Please, first read the README instructions and try to bring the project up and running. If you struggle with that, no problem, ask for help in the issue and we will help you.
Please let me know as soon as you put the project running locally and then let's tackle some issues. Ok?

Cheers man!

**Comment by tiagostutz** [comment]
Ah we can keep interacting there on the strop-analyzing-api issues. =)

**Comment by lbenicio-ibm** [comment]
Sounds great, thanks! i will try to solve it.
