### ISSUE TITLE
Can you give me a task?

### ISSUE THREAD

**Issue by eduardomrodrigues** [bancodobrasil/stop-analyzing#3]
Hi! I want to colaborate with this project! Do you have a task for me?
Thank's!

**Comment by tiagostutz** [comment]
Hi @eduardomrodrigues !

Absolutely. We have options in frontend and backend development. What do you prefer?

**Comment by tiagostutz** [comment]
@eduardomrodrigues, what about this issue? https://github.com/bancodobrasil/stop-analyzing-embed/issues/17

I think that's a nice one, uh?

**Comment by eduardomrodrigues** [comment]
Hi, @tiagostutz! I can help both, frontend and backend!

**Comment by eduardomrodrigues** [comment]
Yes! This #17 is perferct to me! Thank's so much!
