### ISSUE TITLE
Backend Task!

### ISSUE THREAD

**Issue by vinnicius** [bancodobrasil/stop-analyzing#7]
Hello! Any tasks for a new developer on the town? Currently trying to contribute with backend skills...

**Comment by tiagostutz** [comment]
Hi @vinnicius !! 👋 

Absolutely my friend!! We are currently having a discussion that I think you could contribute to... check this [issue](https://github.com/bancodobrasil/stop-analyzing-api/issues/8)  please

**Comment by tiagostutz** [comment]
Hey @vinnicius, maybe you could take a look at [this issue](https://github.com/bancodobrasil/stop-analyzing-api/issues/11) and share some ideas there. How about that?

**Comment by tiagostutz** [comment]
@vinnicius there's this issue https://github.com/bancodobrasil/stop-analyzing-api/issues/5 that maybe you could be interested in. Just checking! 😉 

Cheers!
