### ISSUE TITLE
Can you give me an issue?

### ISSUE THREAD

**Issue by felipewind** [bancodobrasil/stop-analyzing#8]
Hello!
Can you give me an issue? Perhaps I can help your project.
Most of my background is with mainframe technology, but I guess this knowledge won't help much here :)
But, since last year I'm working with Java. I've already done a simple back-end project that run on Weblogic and nowadays I'm working with Quarkus in a microservice environment. I also have some knowledge of Docker, Prometheus and Grafana.
Because of the current project I'm working, I must learn Javascript and Angular. I intend to start studying Javascript next month.
Thats all!
Thanks

**Comment by tiagostutz** [comment]
Hello, @felipewind ! 👋  Welcome on board.!

I’m pretty sure you can help the project. Currently there are two options: 
1) frontend, that uses React with HTML/CSS and is currently has its issues more focused on CSS
2) backend, that uses Golang with Prisma as A database access layer and Gin as HTTP API router.

You could choose any of them. As you have a fullstack experience, we can work on any type of issue here. 

Let me know wether you prefer backend or frontend and I’ll create an appropriate issue for you. Ok?

**Comment by felipewind** [comment]
Thanks for the fast answer @tiagostutz !

I'm sorry, but I think I won't be able to help your project now.
Nowadays, I'm short with time and I wouldn't be able to learn one of these technologies to help your project.

Congratulations for the idea and best wishes for this project!
