### ISSUE TITLE
Task, task, task, task!!

### ISSUE THREAD

**Issue by hainison** [bancodobrasil/stop-analyzing#9]
How can I help this project? My backgrounds are Java and Javascript, but if you have something in Cobol, I'm in too!

**Comment by tiagostutz** [comment]
Hi @hainison ! 👋🏻 
Welcome to Stop Analyzing..! Glad to have you here..!

So, we have backend and frontend options for contributing. It seems you would prefer backend task, right? Please let me know if you prefer backend or frontend so I can open an issue for you.

Meanwhile you can take some time to read the issue #2 that tells the origin of this project and [this backend issue](https://github.com/bancodobrasil/stop-analyzing-api/issues/5) to know a bit more where we are at the backend development and [this issue](https://github.com/bancodobrasil/stop-analyzing-embed/issues/41) in the frontend dev project.

Feel free to ask anything and we will start asap!

Let's go for it! 🏁

**Comment by tiagostutz** [comment]
Hi there @hainison ! 
What do you think about contributing to this https://github.com/bancodobrasil/stop-analyzing-api/issues/20 ?
